[package]
name = "microservice"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.9.0"
serde = "1.0.210"
serde_json = "1.0.128"
actix-cors = "0.7"

[dependencies.multiversx-sc-snippets]
version = "0.53.0"

[dependencies.interactor]
path = "src/interactor"
